### ISSUE TITLE
Lorenz System and Rössler System

### ISSUE THREAD

**Issue by robertkraeuter** [jiahao42/Reservoir#1]
Can you please explain how you set up your three signals input examples? How are states[] and rossler_states[] defined?

**Comment by jiahao42** [comment]
Take Lorenz System as an example, you can get the code from [wiki](https://en.wikipedia.org/wiki/Lorenz_system#Python_simulation).

Add them to `reservoir.py`:
```python
from scipy.integrate import odeint

rho = 28.0
sigma = 10.0
beta = 8.0 / 3.0

def f(state, t):
  x, y, z = state  # unpack the state vector
  return sigma * (y - x), x * (rho - z) - y, x * y - beta * z  # derivatives

state0 = [1.0, 1.0, 1.0]
t = np.arange(0.0, 40.0, 0.01)

states = odeint(f, state0, t)
```

Then change the config file:
```json
{
    "input": {
        "nodes": 3,
        "functions": [
            "lambda x: states[:, 0]",
            "lambda x: states[:, 1]",
            "lambda x: states[:, 2]"
        ],
        "length": 10000
    },
}
```

**Comment by robertkraeuter** [comment]
First of all, thanks for your fast help. Sadly I got the following error:

Traceback (most recent call last):
  File "reservoir.py", line 200, in <module>
    r.run()
  File "reservoir.py", line 178, in run
    self._run()
  File "reservoir.py", line 153, in _run
    self.dataset[i, self.train_len+1: self.train_len+self.error_len+1] - self.S[i, 0: self.error_len])) / self.error_len)
ValueError: operands could not be broadcast together with shapes (999,) (1000,) 
Program finished! Current node = 400


Any ideas what went wrong?

**Comment by jiahao42** [comment]
Not sure what's wrong, for now, you can set `error_len` to a number < 1000, and it should work fine.

In config:

```json
    "training": {
        "init": 1000,
        "train": 5000,
        "test": 1000,
        "error": 500
    }
```

**Comment by robertkraeuter** [comment]
That solved it for me. Thanks for your help.
